blank_issues_enabled: false
contact_links:
  - name: Nellagration App Help Center
    url: https://support.bolt.new
    about: Official central repository for tips, tricks, tutorials, known issues, and best practices for nellagration.app usage.
  - name: Billing Issues
    url: https://support.bolt.new/Billing-13fd971055d680ebb393cb80973710b6
    about: Instructions for billing and subscription related support
  - name: Discord Chat
    url: https://discord.gg/stackblitz
    about: Build, share, and learn with other Nellagration users in real time.
